config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :bulletins
  resources :users
  resource :session
  get 'signup' => 'users#new'
  get "signin" => "sessions#new"

  resources :users do
    member do
      get :confirm_email
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token
  has_secure_password
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8, allow_blank: true }
  has_one_attached :avatar

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
  
  def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def require_admin
        unless current_user_admin?
          redirect_to root_url, alert: "Unauthorized access!"
        end
    end
      
    def current_user_admin?
        current_user && current_user.admin_user
    end

    helper_method :current_user_admin?

private

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to signin_path, alert: "Please sign in first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end
  
  helper_method :current_user?
  
  
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
      user = User.find_by_email(params[:email].downcase)
      if user = User.authenticate(params[:email], params[:password])
        if user.email_confirmed
          session[:user_id] = user.id
          flash[:notice] = "Welcome back, #{user.name}!"
          redirect_to(session[:intended_url] || user)
          session[:intended_url] = nil
        else
          flash.now[:error] = 'Please activate your account by following the 
          instructions in the account confirmation email'
          render 'new'
        end
      else
        flash.now[:alert] = "Invalid email/password combination!"
        render :new
      end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, notice: "You're now signed out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_signin, except: [:new, :create]
    before_action :require_correct_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:index]


    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          UserMailer.registration_confirmation(@user).deliver
          session[:user_id] = @user.id
          redirect_to root_url, notice: "You rolled a natural 20 on signing up!"
        else
          flash[:error] = "Ooooppss, something went wrong!"
          render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to @user, notice: "Account successfully updated!"
        else
          render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil
        redirect_to root_url, alert: "Account successfully deleted!"
    end

    def confirm_email
        user = User.find_by_confirm_token(params[:id])
        if user
          user.email_activate
          flash[:success] = "Welcome to Sandragon! Please sign in to continue."
          redirect_to signin_url
        else
          flash[:error] = "Sorry. User does not exist"
          redirect_to root_url
        end
    end
      
    private
      
    def user_params
        params.require(:user).
        permit(:name, :email, :password, :password_confirmation, :username, :avatar)
    end

    def require_correct_user
        @user = User.find(params[:id])
        redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
    <div style="background: url('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ14wa8AULYI8c7L-7n3OmmLHq9c5W3HpVgQw&usqp=CAU'); align-items: center;
        min-height: 42em;
        children: [object Object],false,false,[object Object];
        background-size: cover;
        background-position: center;">
    </div>
    <content>
        <section style="text-align:center; background: #0F102F; padding: 6rem;">
            <p style="font-size:1.75rem; line-height: 200%;">Compatible with Dungeons & Dragons® 5e, GURPS® and
                best of all, our very own Sandragon
            </p>
            <p style="font-size:1.75rem; line-height: 200%;">
            Sandragon is made for players by players.
            </p>
            <p style="font-size:1.75rem; line-height: 200%;">
             Gamers want action, they want intrigue, and maybe some bawdy innuendo 
             now and then. What we don’t want is time wasted looking up rules and 
             trouble-shooting software. Sandragon is built to maximize your playtime and minimize bog-downs. With 30 years of playing ttrpgs (table-top role playing games), we’ve learned about the pitfalls of gaming and how to avoid them through experience.
            </p>
            <a href="">Learn More</a>
        </section>
        <section style="text-align:center; background:transparent; font-size:1.75rem; padding:4rem;  ">
            <p style="font-size:1.75rem; margin: 1rem 0px; line-height: 200%;">
            Easy and intuitive tools.
            Everything you need to bring your game to life will be obvious and accessible. You don’t want to look up a tutorial wiki article any time you want to use a feature of our platform, and you won’t have to. No esoteric controls, no hunting for commands. A ttrpg should be as easy to use as a pencil, paper and dice. Sandragon is committed to that ideal.
            Conversation is at the heart of the ttrpg experience. World class group forums and private messaging will ensure communications between GMs and players are easy, apparent and effective. If you have a rules-lawyer in your group (and we know you do), satisfy them fast with the in-game wiki. It will help keep that min-maxer in your group in-check too.
            </p>
        </section>
    </content>

app/views/layouts/_footer.html.slim
hr
footer.footer.p2
  small
    nav
      ul.list-reset
        li.
          | About
        li
          | Contact

app/views/layouts/_header.html.erb
<header class="p2">
  <nav style="background-color:#0F102F; padding: .5rem; 1.5rem">
    <p class="inline-block">
      <%= link_to 'SANDRAGON', root_path, class: 'button text-decoration-none', style:'font-size: 1.5rem;' %>
    </p>
    <p style="float:right; display:inline-block;">
      <% if current_user %>
        <%= link_to current_user.name, current_user %>
        <%= link_to "Account Settings", edit_user_path(current_user) %>
        <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
      <% else %>
        <%= link_to 'Sign Up', signup_path, class: 'button' %>
        <%= link_to 'Sign In', new_session_path, class: 'button' %>
      <% end %>
    </p>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SandragonsNest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>
  <body class="m0">
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :username %>
        <%= f.text_field :username, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
      <li>
        <%= f.label "Profile Photo" %>
        <%= f.file_field :avatar %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
          <%= f.submit "Create Account" %>
      <% else %>
          <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render "form"%>

app/views/users/show.html.erb
<article id="user">
    <div>
      <% if @user.avatar.attached? %>
        <image src="<%=(url_for(@user.avatar))%>" width="80px" style="display:inline-block; border-radius: 50%;">
      <% end %>
      <h1 style="display:inline-block; margin-top: 0px; transform: translateY(-32px);"><%= @user.name %></h1>
      <h2><%= mail_to(@user.email) %></h2>
    </div>
</article>

<footer>
  <nav>
  <% if current_user?(@user)  %>
    <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
    <%= link_to 'Delete Account', @user,
                method: :delete,
                data: { confirm: 'Are you sure you want to permanently delete your account?' },
                class: 'button' %>
  <% end %>
  </nav>
</footer>